id: P000681
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21223
  title: སྙིང་སྡུག་མཛའ་མོ་དྲན་གླུ།
  author: ''
  volumes:
    b6a56d66a3c0492899a963ca3337945e:
      image_group_id: I1KG21268
      title: ''
      volume_number: 1
      total_pages: 176
